name: swgpu-doc-update

on: # specify the build to trigger the automated ci/cd
  permissions:
    contents: write
  push:
    branches:
      - "main"
jobs:
  docker:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Install python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13' 
    - name: Install node
      uses: actions/setup-node@v3
      with:
        node-version: 20.x
    - name: Install dependencies
      run: npm install
    - name: Generate json documentation file
      run: npm run doc
    - name: Generate markdown documentation files
      run: npm run markdown

    - name: Checkout Wiki
      uses: actions/checkout@v4
      with:
        repository: ${{github.repository}}.wiki
        path: ${{github.repository}}.wiki
        persist-credentials: true

    - name: Push to wiki
      run: |
        set -e
        cd $GITHUB_WORKSPACE/${{github.repository}}.wiki
        cp -r $GITHUB_WORKSPACE/docs/markdowns/* .
        git config --local user.email "aliyah.raijin@gmail.com"
        git config --local user.name "jay19240"
        git add .
        git diff-index --quiet HEAD || git commit -m "action: wiki sync" && git push