name: swgpu-doc-update

on: # specify the build to trigger the automated ci/cd
  push:
    branches:
      - "main"
jobs:
  docker:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Install python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13' 
    - name: Install node
      uses: actions/setup-node@v3
      with:
        node-version: 20.x
    - name: Install dependencies
      run: npm install
    - name: Generate json documentation file
      run: npm run doc
    - name: Generate markdown documentation files
      run: npm run markdown

    - name: Copycat
      uses: andstor/copycat-action@v3
      with:
        personal_token: ${{ secrets.PERSONAL_TOKEN }}
        src_path: /docs/markdowns
        dst_path: /.
        dst_owner: jay19240
        dst_repo_name: ${{github.repository}}
        dst_branch: master
        src_branch: main
        src_wiki: false
        dst_wiki: true
        username: jay19240
        email: aliyah.raijin@gmail.com